name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from Git tags
        id: extract_version
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --always)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t timpreble/helloworldapi:${{ env.VERSION }} .
          docker push timpreble/helloworldapi:${{ env.VERSION }}

      - name: Tag latest version
        run: |
          docker tag timpreble/helloworldapi:${{ env.VERSION }} yourusername/helloworldapi:latest
          docker push timpreble/helloworldapi:latest
